name: CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t parrot-ai .
    - name: Check image size
      run: |
        image_size=$(docker images parrot-ai --format "{{.Size}}")
        echo "Image size: $image_size"
        if [[ $image_size == *G* ]]; then
          echo "Warning: Image size is in GB, which may include the LLM"
          exit 1
        fi